version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: encurtador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

  spring-app:
    build:
      context: .  # Certifique-se de que o Dockerfile está no mesmo diretório
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/encurtador
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

networks:
  app-network:
    driver: bridge
